config/routes.rb
Rails.application.routes.draw do
  root to: 'favourites#index'

  resources :favourites do
    collection do
      get :list
      get :reload_table
      get :random
    end

    member do
      get :play
      post :increment_likes
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  def self.create_from_video_data(video_data, id=nil)
    return nil unless Favourite.find_by_uri(video_data.url).nil?

    favourite = Favourite.new(
      uri: video_data.url,
      title: video_data.title,
      likes: 1,
    )

    favourite.id = id unless id.nil?
    raise 'No thumbnail' if video_data.thumbnail.nil?

    favourite.save!
    favourite.save_thumbnail(video_data.thumbnail)
    favourite
  end

  def thumbnail_path
    File.join(media_folder_name, 'thumbnail.jpg')
  end

  def save_thumbnail(thumbnail)
    ensure_folder
    thumbnail_path = local_thumbnail_path
    File.open(thumbnail_path, 'wb:ASCII-8BIT') do |f|
      f.write(thumbnail)
    end
  end

  def delete
    delete_folder
    super
  end

  def destroy
    delete_folder
    super
  end

  def increment_likes
    new_likes = likes + 1
    update!(likes: new_likes)
  end

  private
  def local_thumbnail_path
    File.join(Rails.configuration.media_path, thumbnail_path)
  end

  def ensure_folder
    dirname = File.dirname(local_thumbnail_path)
    FileUtils.mkdir_p(dirname) unless File.exist?(dirname)
  end

  def delete_folder
    dirname = File.dirname(local_thumbnail_path)
    FileUtils.remove_dir(dirname)
  end

  def media_folder_name
    id.to_s + '-' + folder_friendly_title
  end

  def folder_friendly_title
    friendly_title = title.strip.downcase
    friendly_title = friendly_title.gsub(/#|\.|\\|\s|\/|\?|\*|\||\>|\<|\:|\;/, '_')

    friendly_title = friendly_title[0..99] if friendly_title.length > 100
    friendly_title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :set_favourite, only: [:show, :edit, :update, :destroy, :play, :increment_likes]

  # GET /favourites
  # GET /favourites.json
  def index
    @favourites = sort(Favourite.all)
  end

  # GET /favourites/1
  # GET /favourites/1.json
  def show
  end

  # GET /favourites/new
  def new
    @favourite = Favourite.new
  end

  # GET /favourites/1/edit
  def edit
  end

  # POST /favourites
  # POST /favourites.json
  def create
    input = params[:links]
    links = input.split("\r\n")

    links.each do |link|
      video_datas = []


      video_data = Fetcher::All::load(link)
      raise "Nil Video Link #{link}" if video_data.nil?
      video_datas.push(video_data)


      video_datas.each do |video_data|
        Favourite.create_from_video_data(video_data)
      end
    end

    respond_to do |format|
      format.html { redirect_to favourites_url, notice: 'Favourites have been added.'  }
    end
  end

  # PATCH/PUT /favourites/1
  # PATCH/PUT /favourites/1.json
  def update
    respond_to do |format|
      if @favourite.update(favourite_params)
        format.html { redirect_to @favourite, notice: 'Favourite was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    @favourite.destroy
    respond_to do |format|
      format.html { redirect_to favourites_url, notice: 'Favourite was successfully destroyed.' }
    end
  end

  def play
    system('D:/vlc/vlc.exe file:///D:/b.mp4')

    respond_to do |format|
      format.html { redirect_to favourites_url }
    end
  end

  def random
    @favourites = Favourite.all.shuffle
    render "random"
  end

  def list
    @favourites = Favourite.all
    render :partial => "list"
  end

  def reload_table
    respond_to do |format|
      format.js
    end
  end

  def increment_likes
    @favourite.increment_likes
    @favourite.reload

    respond_to do |format|
      format.js
    end
  end

  private
    def sort(favourites)
      favourites.order(likes: :desc, updated_at: :desc)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favourite_params
      params.require(:favourite).permit(:uri, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_form.html.erb
<%= form_with(model: favourite, local: true) do |form| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% favourite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uri %>
    <%= form.text_field :uri, id: :favourite_uri %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :favourite_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favourites/_list.html.erb
 <table>
  <thead>
  <tr>
    <th>Site</th>
    <th>Title</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <% @favourites.each do |favourite| %>
    <tr>
      <td>
        <a href="<%= favourite.uri %>", target="_blank">
          <img src="<%= favourite.thumbnail_path %>" style="max-height:200px;max-width:200px;height:auto;width:auto;"/>
        </a>
      </td>
      <td><%= favourite.title %></td>
      <td><%= link_to 'Show', favourite, remote: true %></td>
      <td><%= link_to 'Edit', edit_favourite_path(favourite), remote: true %></td>
      <td><%= link_to 'Destroy', favourite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'VLC', play_favourite_path(favourite), method: :get, remote: true %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/favourites/_random.html.erb
 <table>
  <thead>
  <tr>
    <th>Site</th>
    <th>Title</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
  <% @favourites.each do |favourite| %>
    <tr id="favourite-<%="#{favourite.id}"%>">
      <td>
        <a href="<%= favourite.uri %>", target="_blank">
          <img src="/<%= favourite.thumbnail_path %>" style="max-height:200px;max-width:200px;height:auto;width:auto;"/>
        </a>
      </td>
      <td><%= favourite.title %></td>
      <td class="likes"><%= link_to "#{favourite.likes}", increment_likes_favourite_path(favourite), method: :post, remote: true %></td>
      <td><%= link_to 'Show', favourite, remote: true %></td>
      <td><%= link_to 'Edit', edit_favourite_path(favourite), remote: true %></td>
      <td><%= link_to 'Destroy', favourite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'VLC', play_favourite_path(favourite), method: :get, remote: true %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/favourites/edit.html.erb
<h1>Editing Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/increment_likes.js.erb
$("#favourite-<%="#{@favourite.id}"%>>.likes>a").text(<%= @favourite.likes %>)

app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
<%= link_to 'Favourites', reload_table_favourites_url, remote: true %>
</h1>

<div id="main">
<%= render "favourites/list" %>
</div>

app/views/favourites/new.html.erb
<h1>New Favourite</h1>

<%= form_tag("/favourites", method: "post") do %>
  <div>
    <%= label_tag(:links, "Links:") %>
    <%= text_area_tag(:links, "", size: "50x20") %>
  </div>
  <div>
    <%= submit_tag("Add") %>
  </div>
<% end %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/random.html.erb
<p id="notice"><%= notice %></p>

<h1>
<%= link_to 'Favourites', reload_table_favourites_url, remote: true %>
</h1>

<div id="main">
<%= render "favourites/random" %>
</div>

app/views/favourites/reload_table.js.erb
$("#main").html("<%= escape_javascript( controller.list )%>");

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uri:</strong>
  <%= @favourite.uri %>
</p>

<p>
  <strong>Title:</strong>
  <%= @favourite.title %>
</p>

<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Npcatalog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= tabs %>
    <%= subtabs %>
    <%= yield %>
  </body>
</html>